### ISSUE TITLE
ValueError: Invalid HTML tag name 'href="https:'

### ISSUE THREAD

**Issue by meedstrom** [bohdanbobrowski/blog2epub#32]
Downloading https://www.wisdomandwonder.com stops on post 1190, which I think is: https://www.wisdomandwonder.com/link/7829/keep-track-of-scoping-type-in-emacs-lisp-buffers

The error sounds like the page just has malformed HTML, but I cannot find it in the page source. Odd.

```
[INFO   ] 1190. Keep track of scoping type in Emacs Lisp Buffers
 Exception in thread Thread-2 (_download_ebook):
 Traceback (most recent call last):
   File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.12/threading.py", line 1012, in run
     self._target(*self._args, **self._kwargs)
   File "/tmp/blog2epub/blog2epub/blog2epub_gui.py", line 440, in _download_ebook
     blog2epub.download()
   File "/tmp/blog2epub/blog2epub/blog2epub_main.py", line 55, in download
     self.crawler.crawl()
   File "/tmp/blog2epub/blog2epub/crawlers/default.py", line 369, in crawl
     art = art_factory.process()
           ^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/blog2epub/blog2epub/crawlers/article_factory/default.py", line 238, in process
     self.tree = fromstring(self.html)
                 ^^^^^^^^^^^^^^^^^^^^^
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 33, in fromstring
     return _parse(data, beautifulsoup, makeelement, **bsargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 79, in _parse
     root = _convert_tree(tree, makeelement)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 152, in _convert_tree
     res_root = convert_node(html_root)
                ^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 216, in convert_node
     return handler(bs_node, parent)
            ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 255, in convert_tag
     handler(child, res)
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 255, in convert_tag
     handler(child, res)
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 255, in convert_tag
     handler(child, res)
   [Previous line repeated 7 more times]
   File "/home/me/.cache/pypoetry/virtualenvs/blog2epub-tOU-dq0N-py3.12/lib/python3.12/site-packages/lxml/html/soupparser.py", line 242, in convert_tag
     res = etree.SubElement(parent, bs_node.name, attrib=attribs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "src/lxml/etree.pyx", line 3205, in lxml.etree.SubElement
   File "src/lxml/apihelpers.pxi", line 184, in lxml.etree._makeSubElement
   File "src/lxml/apihelpers.pxi", line 1736, in lxml.etree._htmlTagValidOrRaise
 ValueError: Invalid HTML tag name 'href="https:'
```

**Comment by bohdanbobrowski** [comment]
I've added some simple exception catch here, so this kind of bug will result with:
```Contents of: https://www.wisdomandwonder.com/article/7840/cb750f-day-34-high-idle can not be parsed. Skipping!```
...so this is not a that serious problem anymore. Closing that issue for now, but in future versions will try to find a way how to parse this kind of pages anyway.

**Comment by meedstrom** [comment]
Good idea!
